# This file was generated by GoReleaser. DO NOT EDIT.
class Kraws < Formula
  desc "KRAWS is short for Key Ring for AWS and allows you to assume roles in your AWS Accounts by authenticating towards your federated IDP"
  homepage "https://github.com/innio-it/kraws"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "http://kraws-artefacts.s3-website.eu-central-1.amazonaws.com/v0.6.1/kraws_0.6.1_darwin_amd64.tar.gz"
    sha256 "6db07a5520bbd9277235f1dd742092252548045e6ab253fcfbcc99e14b58d302"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://kraws-artefacts.s3-website.eu-central-1.amazonaws.com/v0.6.1/kraws_0.6.1_linux_amd64.tar.gz"
      sha256 "25e877c46ea5a8d36bfc840ec85b21c9bdd76f66803469325aba63b38159d6fe"
    end
  end

  def install
    bin.install "kraws"
  end
end
