# This file was generated by GoReleaser. DO NOT EDIT.
class Kraws < Formula
  desc "KRAWS is short for Key Ring for AWS and allows you to assume roles in your AWS Accounts by authenticating towards your federated IDP"
  homepage "https://github.com/innio-it/kraws"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/innio-it/kraws/releases/download/v0.6.0/kraws_0.6.0_darwin_amd64.tar.gz"
    sha256 "5a8a670a45ed6effa8e654dfa22909d63c6314666ef0c343ece91abcd9a17101"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/innio-it/kraws/releases/download/v0.6.0/kraws_0.6.0_linux_amd64.tar.gz"
      sha256 "5ad204c37d3b8736c5ab7d4c61d7ad15cf1e1412410ea2d88e8394464a707870"
    end
  end

  def install
    bin.install "kraws"
  end
end
